fix: minor testing fixes for composable config testing
crashappsec/chalk pull request #73
Opened 2023-10-20 16:41 UTC by indecisivedragon

- [x] Followed the steps in the contributor's guide: https://crashoverride.com/docs/other/contributing#filing-the-pull-request
- [x PR title uses [semantic commit messages](https://nitayneeman.com/posts/understanding-semantic-commit-messages-using-git-and-angular/#fix)
- [x] Filled out the template to a useful degree

## Issue

followup on https://github.com/crashappsec/chalk-internal/issues/851

## Description

This pr enables some tests that were disabled due to chalk bugs

2023-10-20 16:50 UTC, miki725 requested changes

2023-10-20 16:50 UTC, miki725 commented on tests/test_composable.py
> +        config_name = test_config_file.split("/")[-1].removesuffix(".c4m")
```python
>>> pathlib.Path('foo/bar/baz/test.c4m').stem
'test'
```

lets use `.stem` instead

https://docs.python.org/3.12/library/pathlib.html#pathlib.PurePath.stem

```suggestion
        config_name = test_config_file.stem
```

2023-10-20 16:50 UTC, miki725 commented on tests/test_composable.py
> +        config_path = "/".join((CONFIGS / test_config_file).__str__().split("/")[:-1])
no need to use `__str__` generally as there is public `str()` which internally will call it:

```
>>> str(pathlib.Path('foo'))
'foo'
```

as for the rest this gets the directory which pathlib provides already wrapper for it:

```python
>>> str(pathlib.Path('foo/bar/baz/test.c4m').parent)
'foo/bar/baz'
```

https://docs.python.org/3.12/library/pathlib.html#pathlib.PurePath.parent

lets use that instead

```suggestion
        config_path = str((CONFIGS / test_config_file).parent)
```

2023-10-20 16:50 UTC, miki725 commented on tests/test_composable.py
> +            assert current_config == original_config
```suggestion
        original_config = (CONFIGS / test_config_file).read_text()
        assert current_config == original_config
```

pathlib has useful abstractions around IO bits. lets use them whenever possible. similar above for already committed code

2023-10-20 17:23 UTC, miki725 submitted a review, later dismissed

2023-10-20 17:33 UTC, miki725 approved these changes

2023-10-23 15:37 UTC, viega approved these changes
Your Output Looks Outstanding

2023-10-23 15:37 UTC, merged